{% set name = "dbt-databricks" %}
{% set version = "1.10.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 7c78ef31612f0d1f9a73880366c228bbe9a81ff24fb226e3aa6596439cf0abf0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - databricks-sdk >=0.41,<0.48.0
    - databricks-sql-connector >=4.0.0,<5.0.0
    - dbt-adapters >=1.14.3,<2.0
    - dbt-common >=1.12.0,<2.0
    - dbt-core >=1.9.0,<2.0
    - dbt-spark >=1.9.0,<2.0
    - keyring >=23.13.0
    - pydantic >=1.10.0

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/databricks/dbt-databricks
  summary: The Databricks adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - monaldoj
