{% set name = "dbt-databricks" %}
{% set version = "1.10.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 468be03dd9521630d2edc7973bbef719aed8dbc4b11345fdc03d1fc17a30d9e3

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - hatchling
  run:
    - python >={{ python_min }}
    - databricks-sdk >=0.41,<0.48.0
    - databricks-sql-connector >=4.0.0,<5.0.0
    - dbt-adapters >=1.7.0,<2.0
    - dbt-common >=1.10.0,<2.0
    - dbt-core >=1.8.7,<2.0
    - dbt-spark >=1.8.0,<2.0
    - keyring >=23.13.0
    - pandas <2.2.0
    - pydantic >=1.10.0,<2

test:
  imports:
    - dbt
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/databricks/dbt-databricks
  summary: The Databricks adapter plugin for dbt
  license: Apache-2.0
  license_file: License.md

extra:
  recipe-maintainers:
    - monaldoj
